blueprint:
  name: Heating Control Timer for BT Thermostats
  description: >
    # Heating Control Timer for BT Thermostats
    
    **Version 0.2**

    Heating control blueprint for BT Thermostats with timer helper.
    Means, switch HVAC_Mode to *heat* and Temperature to *value* when timer begins and reset to last saved Temperature when timer ends.

    Required = *

  domain: automation
  source_url: https://github.com/StormCh/homeassistant/blob/main/blueprints/heating_control_timer_for_btt.yaml
  input:
    timer_helper:
      name: Timer Helper *
      description: Select the timer helper.
      selector:
        entity:
          domain: timer

    thermostat_target:
      name: Thermostats *
      selector:
        target:
          device:
            integration: better_thermostat
          entity:
            integration: better_thermostat
            domain: climate

    set_bt_temp:
      name: Set Temperature
      description: Set the target temperature
      default: 22
      selector:
        number:
          min: 5
          max: 35
          unit_of_measurement: °C

    trigger_input:
      name: Trigger *
      description: The trigger to start the timer. Example - Press Button, Press Mechanism, Motion Sensor, Contact Sensor, Door Sensor, etc.
      selector:
        entity:
          filter:
            domain:
              - switch
              - light
              - sensor
              - schedule
              - binary_sensor
              - input_boolean
              - input_button
          multiple: true

mode: restart
max_exceeded: silent

variables:
  timer_helper: !input timer_helper
  thermostat_target: !input thermostat_target
  set_bt_temp: !input set_bt_temp
  trigger_input: !input trigger_input

trigger:
  - platform: state
    entity_id: !input trigger_input
    to: "on"
    id: 't0'
  - platform: state
    entity_id: !input trigger_input
    id: 't1'
  #- platform: state
  #  entity_id: !input timer_helper
  #  to: "active"
  - platform: state
    entity_id: !input timer_helper
    to: "idle"
    id: 't2'

condition: []

action:
  - if:
      #- condition: state
      #  entity_id: !input timer_helper
      #  state: "active"
      - condition: trigger
        id:
          - 't0'
          - 't1'
    then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target: !input thermostat_target
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: !input set_bt_temp
        target: !input thermostat_target
    else:
      #- service: climate.set_hvac_mode
      #  data:
      #    hvac_mode: "off"
      #  target: !input thermostat_target
      - service: better_thermostat.restore_saved_target_temperature
        data: {}
        target: !input thermostat_target
