blueprint:
  name: Heating Control Timer for BT Thermostats
  description: "Heating control blueprint for BT Thermostats with timer helper. Means, switch HVAC_Mode to *heat* and Temp to *value* when timer begins and switch HVAC_Mode to *off* and reset Temp when timer ends."
  domain: automation
  source_url: https://github.com/StormCh/homeassistant/blob/main/better-thermostat.yaml
  input:
    timer_helper:
      name: Timer Helper
      description: Select the timer helper.
      selector:
        entity:
          domain: timer
              
    thermostat_target:
      name: Thermostats
      selector:
        target:
          device:
            integration: better_thermostat
          entity:
            integration: better_thermostat
            domain: climate

    set_bt_temp:
      name: Set Temperature
      description: Set the target temperature
      default: 22
      selector:
        number:
          min: 5
          max: 35
          unit_of_measurement: °C

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: timer.start
    event_data:
      entity_id: !input timer_helper
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input timer_helper
condition: []
action:
  - if:
      - condition: event
        entity_id: !input timer_helper
        event_type: timer.start
    then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target: !input thermostat_target
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: !input set_bt_temp
        target: !input thermostat_target
    else:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target: !input thermostat_target
      - service: better_thermostat.restore_saved_target_temperature
        data: {}
        target: !input thermostat_target
