blueprint:
  name: BETATEST ONLY - Heating Control for BT Thermostats
  description: >
    # Heating Control for BT Thermostats

    **Version 0.18.0 beta**

  domain: automation
  source_url: https://github.com/StormCh/homeassistant/blob/main/blueprints/heating_control_for_btt_beta.yaml
  input:
    month_selector:
      name: Month Selector
      description: (Required) Select one or more months for the heating period.
      default: ["10","11","12","1","2","3"]
      selector:
        select:
          options:
            - label: "January"
              value: "1"
            - label: "February"
              value: "2"
            - label: "March"
              value: "3"
            - label: "April"
              value: "4"
            - label: "May"
              value: "5"
            - label: "June"
              value: "6"
            - label: "July"
              value: "7"
            - label: "August"
              value: "8"
            - label: "September"
              value: "9"
            - label: "October"
              value: "10"
            - label: "November"
              value: "11"
            - label: "December"
              value: "12"
          multiple: true
          mode: dropdown

    zone_entity:
      name: Zone
      description: (Required) Zone
      default: home
      selector:
        entity:
          filter:
          - domain:
            - zone
          multiple: false
        
    input_persons:
      name: Person at Zone
      description: (Required) Presence, start heating only if someone (one of there persons) is at zone.
      default: []
      selector:
        entity:
          filter:
            - domain: person
          multiple: true

    bt_times_schedule:
      name: Scheduler
      description: (Required) Used Scheduler. Scheduler can be added in the helpers section in your home assistant settings.
      selector:
        entity:
          domain: schedule

    thermostat_target:
      name: Thermostats
      description: (Required) Choose the thermostats to be used for heating. Choose Entity (not Device).
      selector:
        target:
          entity:
            integration: better_thermostat
            domain: climate
 
    set_bt_temp:
      name: Target Temperature
      description: Set the heating target temperature.
      default: 20
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: °C

    sensor_control:
      name: Sensor Control
      description: (Required) External temperature sensor. If temp is higher than target temperature, then disable thermostat.
      selector:
        entity:
          filter:
            - domain:
                - sensor
              device_class:
                - temperature
          multiple: false

    set_bt_temp_after:
      name: Reset Temperature
      description: Reset the temperature after heating.
      default: 18
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: °C

    timer_helper:
      name: Boost Timer
      description: Required. Timer can be added in the helpers section in your home assistant settings.
      selector:
        entity:
          domain: timer

    set_boost_bt_temp:
      name: Set Boost Temperature
      description: Set the heating boost temperature.
      default: 30
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: °C

mode: queued
max_exceeded: silent

trigger:
  - platform: state #schedule control off trigger
    entity_id: !input bt_times_schedule
    from: "on"
    to: "off"
  - platform: state #schedule control on trigger
    entity_id: !input bt_times_schedule
    from: "off"
    to: "on"
  - platform: state #sensor control trigger
    entity_id: !input sensor_control
  - platform: state #presence at zone trigger
    entity_id: !input input_persons
  - platform: state #booster active trigger
    entity_id: !input timer_helper
    to: "active"
    id: "to_active"
  - platform: state #booster idle trigger
    entity_id: !input timer_helper
    to: "idle"
    id: "to_idle"
  - platform: time_pattern  # every 5 minutes trigger to check conditions
    minutes: /5

condition: []

action:
  - variables:
      var_month_selector: !input month_selector
      var_input_persons: !input input_persons
      var_zone_entity: !input zone_entity
      var_zone_lname: '{{ states[var_zone_entity].name|lower }}' #lowering the name works.
      var_zone_name: '{{ states[var_zone_entity].name }}'
      var_zone_uname: '{{ states[var_zone_entity].name|upper }}' #upper the name works.
      var_set_bt_temp: !input set_bt_temp
      var_set_bt_temp_offset: "{{ ( var_set_bt_temp + 0.5 ) | float }}" # add x degree as offset to avoid rapid on/off switching
      var_set_bt_temp_after: !input set_bt_temp_after
      var_set_boost_bt_temp: !input set_boost_bt_temp
      var_sensor_control: !input sensor_control
      var_is_anybody_home_l: "{{ expand( var_input_persons ) | selectattr('state', 'eq', var_zone_lname) | list | count }}" #lower case
      var_is_anybody_home_n: "{{ expand( var_input_persons ) | selectattr('state', 'eq', var_zone_name) | list | count }}" #normal case
      var_is_anybody_home_u: "{{ expand( var_input_persons ) | selectattr('state', 'eq', var_zone_uname) | list | count }}" #upper case
      var_is_anybody_home: "{{ ( var_is_anybody_home_l + var_is_anybody_home_n + var_is_anybody_home_u ) > 0 }}"

  - if: #booster trigger to idle, reset to after temp
      - condition: trigger
        id: "to_idle"
    then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target: !input thermostat_target
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: "{{ var_set_bt_temp_after }}"
        target: !input thermostat_target

  - if: #booster trigger to active, set to booster temp
      - condition: trigger
        id: "to_active"
    then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target: !input thermostat_target
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: "{{ var_set_boost_bt_temp }}"
        target: !input thermostat_target

  - if: #normal trigger conditions
      - condition: template # is current month in selected months
        value_template: "{{ var_month_selector is defined and var_month_selector|length > 0 and now().month | string in var_month_selector }}"
      - condition: state # and selected schedule turns to on
        entity_id: !input bt_times_schedule
        state: "on"
      - condition: template # and is anybody at home
        value_template: "{{ var_is_anybody_home == true }}"
      - condition: state # boost timer is not active
        entity_id: !input timer_helper
        state: idle

    then:
      - if: # if temperature of sensor is above target temperature AND above target temperature with offset
        - condition: numeric_state
          entity_id: !input sensor_control
          above: !input set_bt_temp
        - condition: template
          value_template: "{{ states( var_sensor_control ) | float > var_set_bt_temp_offset | float }}"

        then: # set thermostate to 5deg then wait X sec then set to after temp then set hvac to off
          - service: better_thermostat.set_temp_target_temperature
            data:
              temperature: 5.0
            target: !input thermostat_target
          - delay:
              seconds: 60
          - service: better_thermostat.set_temp_target_temperature
            data:
              temperature: "{{ var_set_bt_temp_after }}"
            target: !input thermostat_target
          - service: climate.set_hvac_mode
            data:
              hvac_mode: 'off'
            target: !input thermostat_target            

        else: # set thermostate to heat and set target temperature
          - service: climate.set_hvac_mode
            data:
              hvac_mode: heat
            target: !input thermostat_target
          - service: better_thermostat.set_temp_target_temperature
            data:
              temperature: "{{ var_set_bt_temp }}"
            target: !input thermostat_target

    else:
      - if:
        - condition: state  # boost timer is idle
          entity_id: !input timer_helper
          state: idle

        then: #reset temperature after
          - if: # if temperature of sensor is above target temperature after
            - condition: numeric_state
              entity_id: !input sensor_control
              above: !input set_bt_temp_after
            - condition: template
              value_template: "{{ states(var_sensor_control) | float > var_set_bt_temp | float }}"

            then:
              - service: better_thermostat.set_temp_target_temperature
                data:
                  temperature: 5.0
                target: !input thermostat_target
              - delay:
                  seconds: 60
              - service: better_thermostat.set_temp_target_temperature
                data:
                  temperature: "{{ var_set_bt_temp_after }}"
                target: !input thermostat_target
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: 'off'
                target: !input thermostat_target

            else:
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: heat
                target: !input thermostat_target
              - service: better_thermostat.set_temp_target_temperature
                data:
                  temperature: "{{ var_set_bt_temp_after }}"
                target: !input thermostat_target
        
        else: # timer boost is active

