blueprint:
  name: Heating Control Schedule for BT Thermostats
  description: >
    # Heating Control Schedule for BT Thermostats

    **Version 0.2**

    Heating control blueprint for BT Thermostats if Schedule event is active.
    Means, switch HVAC_Mode to *heat* and Temperature to *value* when schedule begins and reset last saved Temperature when schedule ends.

    ## History

    ### Version 0.1

    initial Version

    ### Version 0.2

    reset temperature to X after heating

  domain: automation
  source_url: https://github.com/StormCh/homeassistant/blob/main/blueprints/heating_control_for_btt.yaml
  input:
    bt_times_schedule:
      name: Schedule helper
      selector:
        entity:
          domain: schedule

    thermostat_target:
      name: Thermostats
      selector:
        target:
          device:
            integration: better_thermostat
          entity:
            integration: better_thermostat
            domain: climate

    set_bt_temp:
      name: Set Temperature
      description: Set the target temperature
      default: 20
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: °C

    set_bt_temp_after:
      name: Reset Temperature
      description: Reset the Temperature to after Heating
      default: 17
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: °C

mode: queued
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input bt_times_schedule
    from: "on"
    to: "off"
  - platform: state
    entity_id: !input bt_times_schedule
    from: "off"
    to: "on"
condition: []
action:
  - if:
      - condition: state
        entity_id: !input bt_times_schedule
        state: "on"
    then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target: !input thermostat_target
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: !input set_bt_temp
        target: !input thermostat_target
    else:
      #- service: climate.set_hvac_mode
      #  data:
      #   hvac_mode: "off"
      #  target: !input thermostat_target
      #- service: better_thermostat.restore_saved_target_temperature
      #  data: {}
      #  target: !input thermostat_target
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: !input set_bt_temp_after
        target: !input thermostat_target
